<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MovieSync.Application\MovieSync.Application.csproj" />
    <ProjectReference Include="..\MovieSync.Infrastructure\MovieSync.Infrastructure.csproj" />
    <ProjectReference Include="..\MovieSync.Domain\MovieSync.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
